### ISSUE TITLE
OCaml 5.4.1 support

### ISSUE THREAD

**Issue by kit-ty-kate** [xavierleroy/ocamlmpi#13]
Currently mpi fails to build with OCaml >= 5.4.1:
```
#=== ERROR while compiling mpi.1.06 ===========================================#
# context              2.5.0 | linux/x86_64 | ocaml-variants.5.5.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.5/.opam-switch/build/mpi.1.06
# command              /usr/bin/make all MPIINCDIR=/usr/lib/x86_64-linux-gnu/openmpi/include MPILIBDIR=/usr/lib/x86_64-linux-gnu/openmpi/lib/lib MPICC=/usr/lib/x86_64-linux-gnu/openmpi/lib/bin/mpicc MPIRUN=/usr/lib/x86_64-linux-gnu/openmpi/lib/bin/mpirun
# exit-code            2
# env-file             ~/.opam/log/mpi-14-4e7e95.env
# output-file          ~/.opam/log/mpi-14-4e7e95.out
### output ###
# cc -I`ocamlc -where` -I/usr/lib/x86_64-linux-gnu/openmpi/include -O2 -g -Wall -DCAML_NAME_SPACE   -c -o init.o init.c
# cc -I`ocamlc -where` -I/usr/lib/x86_64-linux-gnu/openmpi/include -O2 -g -Wall -DCAML_NAME_SPACE   -c -o comm.o comm.c
# cc -I`ocamlc -where` -I/usr/lib/x86_64-linux-gnu/openmpi/include -O2 -g -Wall -DCAML_NAME_SPACE   -c -o msgs.o msgs.c
# msgs.c: In function 'caml_mpi_receive':
# msgs.c:151:9: error: too few arguments to function 'caml_input_value_from_malloc'
#   151 |   res = caml_input_value_from_malloc(buffer, 0);
#       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
# In file included from msgs.c:21:
# /home/opam/.opam/5.5/lib/ocaml/caml/intext.h:171:18: note: declared here
#   171 | CAMLextern value caml_input_value_from_malloc(char * data, intnat ofs,
#       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
# msgs.c: In function 'caml_mpi_wait_receive':
# msgs.c:383:12: error: too few arguments to function 'caml_input_value_from_malloc'
#   383 |   result = caml_input_value_from_malloc(Buffer_req_val(req), 0);
#       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
# /home/opam/.opam/5.5/lib/ocaml/caml/intext.h:171:18: note: declared here
#   171 | CAMLextern value caml_input_value_from_malloc(char * data, intnat ofs,
#       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
# make: *** [<builtin>: msgs.o] Error 1
```
The `caml_input_value_from_malloc` function was modified in https://github.com/ocaml/ocaml/commit/3aa27e4d2522950b2fe2acf868591209e93d1377 (trunk) / https://github.com/ocaml/ocaml/commit/508d35d970a70a39ea2c9d9241ae4587a9b3a96a (5.5) / https://github.com/ocaml/ocaml/commit/e3919fef436f89271bc30bbe8592851f7289fb68 (5.4.1)

**Comment by xavierleroy** [comment]
Thanks for the ping!  I'm the one who pushed for this change of type of `caml_input_value_from_malloc`, and I promised to update OCamlMPI to accommodate the change, and I forgot to do it.  I'm pushing a fix ASAP and will make a new OPAM package this week.
